Finished fixing up environment variable files

diff --git a/home/shell/environment/editor b/home/shell/environment/editor
--- a/home/shell/environment/editor
+++ b/home/shell/environment/editor
@@ -1,10 +1,16 @@
 #!/bin/sh
 
-if [ -n $SSH_TTY ]; then
-    export EDITOR=subl
+source $HOME/.shell/environment/ssh
+if [ $IS_SSH -eq 0 ] && type subl >/dev/null 2>&1 then
+    export EDITOR=$(which subl)
+elif type vim >/dev/null 2>&1
+    export EDITOR=$(which vim)
 else
-    export EDITOR=vim
+    echo "Unable to set EDITOR environment variable" >&2
 fi
 
+# The `less` pager supports editing the file being viewed by pressing "v".
 export LESSEDIT=$EDITOR
+
+# VISUAL is basically the same as EDITOR.
 export VISUAL=$EDITOR
diff --git a/home/shell/environment/pager b/home/shell/environment/pager
--- a/home/shell/environment/pager
+++ b/home/shell/environment/pager
@@ -1,13 +1,16 @@
 #!/bin/sh
 
 # Use `less` as the default pager.
-export PAGER=less
+if type less >/dev/null 2>&1; then
+    export PAGER=$(which less)
+else
+    echo "Unable to set PAGER environment variable" >&2
+fi
 
-# Less flags.
+# Allow `less` to show color escape sequences.
 export LESS='-R'
 
-# Get color support for `less`.
-export LESS='$LESS --RAW-CONTROL-CHARS'
-
-# Set the Less input preprocessor.
-type lesspipe >/dev/null 2>&1 && eval $(lesspipe)
+# Set the less input preprocessor.
+if type lesspipe >/dev/null 2>&1; then
+    eval $(lesspipe)
+fi
