Tidied up the shell functions a bit

diff --git a/home/shell/functions/archive b/home/shell/functions/archive
--- a/home/shell/functions/archive
+++ b/home/shell/functions/archive
@@ -7,7 +7,7 @@
 #
 # @link http://nparikh.org/notes/zshrc.txt
 #
-extract () {
+extract() {
     if [ -f $1 ]; then
         case $1 in
             *.tar.bz2)  tar -jxvf $1                        ;;
@@ -23,9 +23,11 @@ extract () {
             *.pax)      cat $1 | pax -r                     ;;
             *.pax.Z)    uncompress $1 --stdout | pax -r     ;;
             *.Z)        uncompress $1                       ;;
-            *)          echo "'$1' cannot be extracted/mounted via extract()" >&2 ; return 1 ;;
+            *)
+                echo "'$1' cannot be extracted/mounted via extract()" >&2
+                return 1
+                ;;
         esac
-        return $?
     else
         echo "'$1' is not a valid file" >&2
         return 2
